export const orderList = {
  totalPages: 14,
  totalElements: 40,
  first: true,
  last: true,
  size: 3,
  content: [
    {
      id: 1,
      category: '버거',
      storeName: '버거킹전남대점1',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 2,
      category: '버거',
      storeName: '버거킹전남대점2',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: true,
    },
    {
      id: 3,
      category: '버거',
      storeName: '버거킹전남대점3',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 4,
      category: '버거',
      storeName: '버거킹전남대점4',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 5,
      category: '버거',
      storeName: '버거킹전남대점5',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 6,
      category: '버거',
      storeName: '버거킹전남대점6',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 7,
      category: '버거',
      storeName: '버거킹전남대점7',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 8,
      category: '버거',
      storeName: '버거킹전남대점8',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 9,
      category: '버거',
      storeName: '버거킹전남대점9',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 10,
      category: '버거',
      storeName: '버거킹전남대점10',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 11,
      category: '버거',
      storeName: '버거킹전남대점11',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 12,
      category: '버거',
      storeName: '버거킹전남대점12',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 13,
      category: '버거',
      storeName: '버거킹전남대점13',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 14,
      category: '버거',
      storeName: '버거킹전남대점14',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 15,
      category: '버거',
      storeName: '버거킹전남대점15',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 16,
      category: '버거',
      storeName: '버거킹전남대점16',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 17,
      category: '버거',
      storeName: '버거킹전남대점17',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 18,
      category: '버거',
      storeName: '버거킹전남대점18',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 19,
      category: '버거',
      storeName: '버거킹전남대점19',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 20,
      category: '버거',
      storeName: '버거킹전남대점20',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 21,
      category: '버거',
      storeName: '버거킹전남대점21',
      minimumOrderAmount: 3,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: true,
      price: 11900,
      isCreater: false,
    },
    {
      id: 22,
      category: '중식',
      storeName: '스피드반점22',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 12900,
      isCreater: true,
    },
    {
      id: 23,
      category: '아시안',
      storeName: '한솥도시락23',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 9000,
      isCreater: true,
    },
    {
      id: 24,
      category: '돈까스,회,일식',
      storeName: '루키초밥24',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 30000,
      isCreater: true,
    },
    {
      id: 25,
      category: '돈까스,회,일식',
      storeName: '상무초밥25',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
    {
      id: 26,
      category: '돈까스,회,일식',
      storeName: '상무초밥26',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
    {
      id: 27,
      category: '돈까스,회,일식',
      storeName: '상무초밥27',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
    {
      id: 28,
      category: '돈까스,회,일식',
      storeName: '상무초밥28',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
    {
      id: 29,
      category: '돈까스,회,일식',
      storeName: '상무초밥29',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
    {
      id: 30,
      category: '돈까스,회,일식',
      storeName: '상무초밥30',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
    {
      id: 31,
      category: '돈까스,회,일식',
      storeName: '상무초밥31',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
    {
      id: 32,
      category: '돈까스,회,일식',
      storeName: '상무초밥32',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
    {
      id: 33,
      category: '돈까스,회,일식',
      storeName: '상무초밥33',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
    {
      id: 34,
      category: '돈까스,회,일식',
      storeName: '상무초밥34',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
    {
      id: 35,
      category: '돈까스,회,일식',
      storeName: '상무초밥35',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
    {
      id: 36,
      category: '돈까스,회,일식',
      storeName: '상무초밥36',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
    {
      id: 37,
      category: '돈까스,회,일식',
      storeName: '상무초밥37',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
    {
      id: 38,
      category: '돈까스,회,일식',
      storeName: '상무초밥38',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
    {
      id: 39,
      category: '돈까스,회,일식',
      storeName: '상무초밥39',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
    {
      id: 40,
      category: '돈까스,회,일식',
      storeName: '상무초밥40',
      minimumOrderAmount: 4,
      pickUpLocation: '경기 용인시 수지구 용구대로 2770',
      deliveryStatus: false,
      price: 15000,
      isCreater: true,
    },
  ],
  number: 0,
  sort: {
    empty: false,
    unsorted: false,
    sorted: true,
  },
  pageable: {
    pageNumber: 0,
    pageSize: 3,
    sort: {
      empty: false,
      unsorted: false,
      sorted: true,
    },
    offset: 0,
    unpaged: false,
    paged: true,
  },
  numberOfElements: 2,
  empty: false,
};
