export const storeList = [
  {
    id: '1',
    image: '/image/restaurant.png',
    category: '분식',
    storeName: '이삭토스트',
    minimumOrderAmount: 10000,
    pickUpLocation: '경기 용인시 수지구 용구대로 2770',
    deadlineTime: '오후 1시 50분',
  },
  {
    id: '2',
    image: '/image/restaurant.png',
    category: '족발·보쌈',
    storeName: '장충동 왕족발',
    minimumOrderAmount: 10000,
    pickUpLocation: '경기 용인시 수지구 용구대로 2770',
    deadlineTime: '오후 1시 50분',
  },
  {
    id: '3',
    image: '/image/restaurant.png',
    category: '버거',
    storeName: '버거킹',
    minimumOrderAmount: 10000,
    pickUpLocation: '경기 용인시 수지구 용구대로 2770',
    deadlineTime: '오후 1시 50분',
  },
  {
    id: '4',
    image: '/image/restaurant.png',
    category: '버거',
    storeName: '맥도날드',
    minimumOrderAmount: 10000,
    pickUpLocation: '경기 용인시 수지구 용구대로 2770',
    deadlineTime: '오후 1시 50분',
  },
];
